// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://kbsvryszfigdmqfjjmka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtic3ZyeXN6ZmlnZG1xZmpqbWthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MjYxMTUsImV4cCI6MjA2ODQwMjExNX0.cT_v0QxSENR0g5E3w_oz1Dc6I_OG5y1v6fzevXsSa7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);